services:
    frontend:
        build: .
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.sandbox_front.rule=Host(`sandbox.bleit.ru`)'
            - 'traefik.http.routers.sandbox_front.entrypoints=websecure'
            - 'traefik.http.routers.sandbox_front.tls=true'
            - 'traefik.http.routers.sandbox_front.tls.certresolver=myresolver'
            - 'traefik.http.services.sandbox_front.loadbalancer.server.port=80'
        networks:
            - web

networks:
    web:
        external: true
